name: Markdown CI

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/*"
      - ".markdownlint.yaml"
      - "**/*.md"
  pull_request:
    branches:
      - master
    paths:
      - ".github/workflows/*"
      - ".markdownlint.yaml"
      - "**/*.md"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: "**/*.md"
          config_file: .markdownlint.yaml
          dot: true
